### ISSUE TITLE
no luks encryption

### ISSUE THREAD

**Issue by ghost** [calamares/calamares-manjaro#12]
No luks encryption

in german and english gui of calamares the checkbox for activating luks encryption is missing.
[See here](http://www.fotos-hochladen.net/uploads/calamarest3rwnox9fz.png)
[I used this image:](http://sourceforge.net/projects/manjarolinux/files/release/16.06-rc1/xfce/manjaro-xfce-16.06-rc1-x86_64.iso)
download 2016-05-24, verified by sha1sum and gpg

after installation from this image i can choose manjaro and opensuse 13.2 in grub. I have never installed opensuse.

**Comment by hphilm** [comment]
@shelby-cobra: this is not a bug. Luks encryption is only supporte with the **calamares-dev** package and not with the current stable **v2.2** series. Please download the current **kde development build** or **mage development build** to have this feature on a ISO.

**Comment by ghost** [comment]
thanks for your message. i tried to install manjaro mate from manjaro
testing repository. i could activate luks encryption, but got an error,
see appendix. i think, i'll wait til luks is part of the stable branch

mit freundlichen Grüßen
Andreas Manthey
Im Meinecken Sohl 38 B
38518 Gifhorn
05371 170 26 35

Am 24.05.2016 um 21:37 schrieb Philip Müller:
