### ISSUE TITLE
Manual partitioning could remember flags on re-edit

### ISSUE THREAD

**Issue by freed00m** [calamares/calamares-manjaro#13]
Hi, it's a small feature request

I am using calamares-dev to install community i3 version of manjaro.

I don't want to have swap on SSD drive and I had to do manual partitioning.

The process works fine, but when selecting flags I expected to see them on reentry the partition options when clicking EDIT from a menu, they all unselect and it gave me impression of something have gone wrong.

**Comment by hphilm** [comment]
@freed00m: please open feature requests in the [upstream project](https://calamares.io/bugs).
