### ISSUE TITLE
calamares.svg file that doesn't exist.

### ISSUE THREAD

**Issue by NuLogicSystems** [calamares/calamares-manjaro#2]
I adopted your profile and pkgbuild for calamares 2.0.
We use a calamares.png file that is getting put under icons but so is a small non existent calamares.svg.

**Comment by NuLogicSystems** [comment]
Here is my modified pkgbuild: http://pastebin.com/c9zmn7fU

**Comment by AJSlye** [comment]
OK, I fixed it. I do apologize, it was just an oversight in where the PKGBUILD was copying the file to.

**Comment by NuLogicSystems** [comment]
I edited the PKGBUILD and thought it was fixed, but it's not.
I changed this line:
install -Dm644 "../data/calamares.png" "$pkgdir/usr/share/icon/hicolor/scalable/apps/calamares.png"
to:
install -Dm644 "../data/calamares.png" "$pkgdir/usr/share/icons/calamares.png"

So now what could be creating this file?
/usr/share/icons/hicolor/scalable/apps/calamars.svg

**Comment by hphilm** [comment]
There is no problem here at **Manjaro**, seems to be **Netrunner** specific, as we have `install -Dm644 "../data/manjaro-icon.svg" "$pkgdir/usr/share/icons/hicolor/scalable/apps/calamares.svg"`

**Comment by hphilm** [comment]
More or less you have to look at https://github.com/calamares/calamares/commit/6ec2b07ca7d881d6871e2a2455998a7b7e4c0653

**Comment by NuLogicSystems** [comment]
I know I figured out what was doing it at 1:00 am. I'm using your pkgbuild and editing it for Netrunner, but your copying over it, I unfortunately only have the png file and can't do the same thing.  I know there is a way to edit this line out from in the pkgbuild but I'm not quite sure how to do this yet.

**Comment by hphilm** [comment]
Following line should remove the upstream image: `rm "$pkgdir/usr/share/icons/hicolor/scalable/apps/calamares.svg"`. Install your png image as usual.

**Comment by NuLogicSystems** [comment]
Yea, I already tried that, it  came back with a file not does not exist error. I put this line down where the install lines are, is somewhere else this should go?

**Comment by hphilm** [comment]
Then you have to create an **svg** icon.

**Comment by NuLogicSystems** [comment]
it's copying the squid icon from ${CMAKE_SOURCE_DIR}/data/images/squid.svg where ever that is. right now my package has both of these images in it.

**Comment by hphilm** [comment]
It is just a stupied svg image. You can either revert that commit or delete it. Shouldn't be so hard. Print me the error you get. Is it from Calamares or from the PKGBUILD?

**Comment by NuLogicSystems** [comment]
I put the rm "$pkgdir/usr/share/icons/hicolor/scalable/apps/calamares.svg" near the end of the file at in the package section right after the install lines. Should I be putting this somewhere else?

**Comment by hphilm** [comment]
The proper place would be after `make install`, don't you think?

**Comment by AJSlye** [comment]
do you mean this line: make DESTDIR="$pkgdir" install

**Comment by NuLogicSystems** [comment]
Stupid me, if it were a snake!!
I had rm -r "$pkgdir/usr/share/icons/hicolor/scalable/apps/calamares.svg", remove the -r and well, duh.

**Comment by AJSlye** [comment]
But it still leaves the /usr/share/icons/hicolor/scalable/apps/ directory so I added rm -r "$pkgdir/usr/share/icons/hicolor/scalable/apps/" under it.

**Comment by hphilm** [comment]
This would be the proper solution:

```
    install -Dm644 "../data/calamares.png" "$pkgdir/usr/share/icons/hicolor/48x48/apps/calamares.png"
    install -Dm644 "../data/calamares.png" "$pkgdir/usr/share/icons/calamares.png"
    rm -r "$pkgdir/usr/share/icons/hicolor/scalable"
```

**Comment by NuLogicSystems** [comment]
Thanks philip, it was late and I wasn't thinking straight last night. I do appreciate it.
