### ISSUE TITLE
postcfg - we should find a way to configure root account also

### ISSUE THREAD

**Issue by hphilm** [calamares/calamares-manjaro#27]
We need something similar for:

```
    # Configure root user
    cp /etc/skel/.{bash_profile,bashrc,bash_logout,extend.bashrc} /root/
    if [[ -d /etc/skel/.config ]];then
        cp -a /etc/skel/.config /root/
    fi
```

**Comment by udeved** [comment]
Not sure, but how do other distros configure /root?
In my opinion, besides bash stuff, we shouldn't copy .config
After all. it is root account, gui apps shouldn't be run as root, and user should be reminded of that, a bad ugly theme is ideal for as reminder. :)

**Comment by udeved** [comment]
@guinux 

I see one slight "problem" with the mirror addition.
If we deploy a pure offline iso, the ranking fails.
Perhaps we add a check, if globalstorage hasInternet...

**Comment by hphilm** [comment]
@udeved: I don't get the combination of the commit Guillaume did and the question on how to configure the root account ...

**Comment by hphilm** [comment]
https://github.com/calamares/calamares-manjaro/commit/0ef92374dd45321292d2d5dc0985d669cfda519e

**Comment by udeved** [comment]
Well, you talk root account, I talk mirror PR. :)

I think its bad practise to configure apps in root account, and potential security risk.

**Comment by udeved** [comment]
I see, oops, I read postcfg in title and confused it with the other one where you talked root account too. :)

**Comment by hphilm** [comment]
https://github.com/calamares/calamares-manjaro/commit/ae2a312fba87a35d68a6ad6ea0d8be769d6b04f2
