### ISSUE TITLE
Allow hostnames to start with numbers

### ISSUE THREAD

**Issue by ChazyTheBest** [calamares/calamares-manjaro#3]
Is there any reason why not to allow hostnames to start with a number? It is legal and accepted: http://tools.ietf.org/html/rfc1123#page-13

**Comment by hphilm** [comment]
Please open an issue to the [upstream bugtracker](https://calamares.io/bugs/). We only maintain here **Manjaro Linux** specific modules.

**Comment by ChazyTheBest** [comment]
Ah ok sorry.
