### ISSUE TITLE
[GRUB cfg] Duplicated GRUB_ENABLE_CRYPTODISK

### ISSUE THREAD

**Issue by Querulous** [calamares/calamares-manjaro#40]
After Manjaro installation using Calamares with this partition schema:
/boot (unencrypted)
/boot/efi (unencrypted)
/ (encrypted)

There is duplicated entry for GRUB_ENABLE_CRYPTODISK in /etc/default/grub. Lines 16 & 50 in my case. First one is commented but second one isn't.

I see two problems here:
1. Duplicated GRUB_ENABLE_CRYPTODISK - if config file hasn't been changed by user you could except there will be only one entry for every option
2. Calamares do not respect user settings when /boot & /boot/efi are unencrypted.

Tested on manjaro-kde-20.0.1-200511-linux56.iso but I've checked /etc/default/grub on system installed more then year ago ( with encrypted both boot partitions ) and there GRUB_ENABLE_CRYPTODISK is also duplicated.

**Comment by abucodonosor** [comment]
That's because this setup is not supported. Search the bug tracker for unencrypted /boot

**Comment by Querulous** [comment]
Did you mean github bug tracker?

Also looks kinda supported for me:
https://imgur.com/emR2P6c

**Comment by kkofler** [comment]
The upstream Calamares bug tracker:
https://github.com/calamares/calamares/issues/1083

**Comment by kkofler** [comment]
and:
https://github.com/calamares/calamares/issues/1073

**Comment by Querulous** [comment]
Thanks for links.

For completeness this would be more relevant [calamares/calamares/issues/1311](https://github.com/calamares/calamares/issues/1311).
[](url)
Then there is misleading error prompt when /boot is unencrypted (printscreen in my post above) but I assume calamares/calamares would be better place to report it.

**Comment by kkofler** [comment]
Yes, this message comes from upstream Calamares.
