### ISSUE TITLE
[enhancement] Encryption passphrase validation

### ISSUE THREAD

**Issue by Querulous** [calamares/calamares-manjaro#41]
It would be nice if installer would check if passphrase contains any characters (non-English characters?) that will make unlocking encrypted drive by grub impossible.

Tested on: manjaro-kde-20.0.1-200511-linux56.iso

**Comment by abucodonosor** [comment]
Grub default is English keyboard layout only unless you have special grub core images.

What do you want to check? And how do you want to check that?

And btw why are you opening these bugs in calamares-manjaro?

( discuss about this issue exists in the main bug tracker )
